import joblib


class TextProfanityFilter:
    def __init__(self) -> None:
        # Load the saved model and vectorizer
        self.model = joblib.load("model/offensive_classifier.joblib")
        self.vectorizer = joblib.load("model/tfidf_vectorizer.joblib")

        self.moderated_json = []  # List for filtered text

        # Replacements for text
        self.replacements = {
            "0": "o",
            "1": "i",
            "3": "e",
            "4": "a",
            "5": "s",
            "7": "l",
            "$": "s",
            "!": "i",
            "+": "t",
            "#": "h",
            "@": "a",
            "<": "c",
        }

        # All Good words
        self.goodwords = [
            # Articles / Determiners
            "a",
            "an",
            "the",
            # Auxiliary / Linking Verbs
            "is",
            "are",
            "was",
            "were",
            "be",
            "been",
            "being",
            # Pronouns
            "I",
            "you",
            "he",
            "she",
            "it",
            "we",
            "they",
            "me",
            "him",
            "her",
            "us",
            "them",
            "my",
            "your",
            "his",
            "her",
            "its",
            "our",
            "their",
            # Question Words (Interrogatives)
            "who",
            "what",
            "when",
            "where",
            "why",
            "how",
            "whom",
            "which",
            # Conjunctions
            "and",
            "but",
            "or",
            "so",
            "yet",
            "for",
            "nor",
            # Prepositions
            "in",
            "on",
            "at",
            "by",
            "with",
            "about",
            "against",
            "between",
            "into",
            "through",
            # Adverbs
            "also",
            "very",
            "too",
            "not",
            "just",
            "only",
            "still",
            "already",
            # Modals
            "can",
            "could",
            "will",
            "would",
            "shall",
            "should",
            "may",
            "might",
            "must",
        ]

        # All Bad Words
        self.badwords = [
            "2 girls 1 cup",
            "anal",
            "anus",
            "areole",
            "arian",
            "arrse",
            "arse",
            "arsehole",
            "aryan",
            "asanchez",
            "ass",
            "assbang",
            "assbanged",
            "asses",
            "assfuck",
            "assfucker",
            "assfukka",
            "asshole",
            "assmunch",
            "asswhole",
            "autoerotic",
            "ballsack",
            "bastard",
            "bdsm",
            "beastial",
            "beastiality",
            "bellend",
            "bestial",
            "bestiality",
            "bimbo",
            "bimbos",
            "bitch",
            "bitches",
            "bitchin",
            "bitching",
            "blowjob",
            "blowjobs",
            "blue waffle",
            "bondage",
            "boner",
            "boob",
            "boobs",
            "booobs",
            "boooobs",
            "booooobs",
            "booooooobs",
            "booty call",
            "breasts",
            "brown shower",
            "brown showers",
            "buceta",
            "bukake",
            "bukkake",
            "bullshit",
            "busty",
            "butthole",
            "carpet muncher",
            "cawk",
            "chink",
            "cipa",
            "clit",
            "clitoris",
            "clits",
            "cnut",
            "cock",
            "cockface",
            "cockhead",
            "cockmunch",
            "cockmuncher",
            "cocks",
            "cocksuck",
            "cocksucked",
            "cocksucker",
            "cocksucking",
            "cocksucks",
            "cokmuncher",
            "coon",
            "cowgirl",
            "cowgirls",
            "crap",
            "crotch",
            "cum",
            "cuming",
            "cummer",
            "cumming",
            "cums",
            "cumshot",
            "cunilingus",
            "cunillingus",
            "cunnilingus",
            "cunt",
            "cuntlicker",
            "cuntlicking",
            "cunts",
            "damn",
            "deepthroat",
            "dick",
            "dickhead",
            "dildo",
            "dildos",
            "dink",
            "dinks",
            "dlck",
            "dog style",
            "dog-fucker",
            "doggiestyle",
            "doggin",
            "dogging",
            "doggystyle",
            "dong",
            "donkeyribber",
            "doofus",
            "doosh",
            "dopey",
            "douche",
            "douchebag",
            "douchebags",
            "douchey",
            "drunk",
            "duche",
            "dumass",
            "dumbass",
            "dumbasses",
            "dummy",
            "dyke",
            "dykes",
            "eatadick",
            "eathairpie",
            "ejaculate",
            "ejaculated",
            "ejaculates",
            "ejaculating",
            "ejaculatings",
            "ejaculation",
            "ejakulate",
            "enlargement",
            "erect",
            "erection",
            "erotic",
            "erotism",
            "essohbee",
            "extacy",
            "extasy",
            "facial",
            "fack",
            "fag",
            "fagg",
            "fagged",
            "fagging",
            "faggit",
            "faggitt",
            "faggot",
            "faggs",
            "fagot",
            "fagots",
            "fags",
            "faig",
            "faigt",
            "fanny",
            "fannybandit",
            "fannyflaps",
            "fannyfucker",
            "fanyy",
            "fart",
            "fartknocker",
            "fat",
            "fatass",
            "fcuk",
            "fcuker",
            "fcuking",
            "feck",
            "fecker",
            "felch",
            "felcher",
            "felching",
            "fellate",
            "fellatio",
            "feltch",
            "feltcher",
            "femdom",
            "fingerfuck",
            "fingerfucked",
            "fingerfucker",
            "fingerfuckers",
            "fingerfucking",
            "fingerfucks",
            "fingering",
            "fisted",
            "fistfuck",
            "fistfucked",
            "fistfucker",
            "fistfuckers",
            "fistfucking",
            "fistfuckings",
            "fistfucks",
            "fisting",
            "fisty",
            "flange",
            "flogthelog",
            "floozy",
            "foad",
            "fondle",
            "foobar",
            "fook",
            "fooker",
            "footjob",
            "foreskin",
            "freex",
            "frigg",
            "frigga",
            "fubar",
            "fuck",
            "fucka",
            "fuckass",
            "fuckbitch",
            "fucked",
            "fucker",
            "fuckers",
            "fuckface",
            "fuckhead",
            "fuckheads",
            "fuckhole",
            "fuckin",
            "fucking",
            "fuckings",
            "fuckingshitmotherfucker",
            "fuckme",
            "fuckmeat",
            "fucknugget",
            "fucknut",
            "fuckoff",
            "fuckpuppet",
            "fucks",
            "fucktard",
            "fucktoy",
            "fucktrophy",
            "fuckup",
            "fuckwad",
            "fuckwhit",
            "fuckwit",
            "fuckyomama",
            "fudgepacker",
            "fuk",
            "fuker",
            "fukker",
            "fukkin",
            "fukking",
            "fuks",
            "fukwhit",
            "fukwit",
            "futanari",
            "futanary",
            "fux",
            "fuxor",
            "fxck",
            "gae",
            "gai",
            "gangbang",
            "gangbanged",
            "gangbangs",
            "ganja",
            "gassyass",
            "gay",
            "gaylord",
            "gays",
            "gaysex",
            "gey",
            "gfy",
            "ghay",
            "ghey",
            "gigolo",
            "glans",
            "goatse",
            "god",
            "godamn",
            "godamnit",
            "goddam",
            "goddammit",
            "goddamn",
            "goddamned",
            "gokkun",
            "goldenshower",
            "gonad",
            "gonads",
            "gook",
            "gooks",
            "gringo",
            "gspot",
            "gtfo",
            "guido",
            "hamflap",
            "handjob",
            "hardcoresex",
            "hardon",
            "hebe",
            "heeb",
            "hell",
            "hemp",
            "hentai",
            "heroin",
            "herp",
            "herpes",
            "herpy",
            "heshe",
            "hitler",
            "hiv",
            "hoar",
            "hoare",
            "hobag",
            "hoer",
            "homey",
            "homo",
            "homoerotic",
            "homoey",
            "honky",
            "hooch",
            "hookah",
            "hooker",
            "hoor",
            "hootch",
            "hooter",
            "hooters",
            "hore",
            "horniest",
            "horny",
            "hotsex",
            "howtokill",
            "howtomurdep",
            "hump",
            "humped",
            "humping",
            "hussy",
            "hymen",
            "inbred",
            "incest",
            "injun",
            "jackass",
            "jackhole",
            "jackoff",
            "jap",
            "japs",
            "jerk",
            "jerked",
            "jerkoff",
            "jism",
            "jiz",
            "jizm",
            "jizz",
            "jizzed",
            "junkie",
            "junky",
            "kawk",
            "kike",
            "kikes",
            "kill",
            "kinbaku",
            "kinky",
            "kinkyJesus",
            "kkk",
            "klan",
            "knob",
            "knobead",
            "knobed",
            "knobend",
            "knobhead",
            "knobjocky",
            "knobjokey",
            "kock",
            "kondum",
            "kondums",
            "kooch",
            "kooches",
            "kootch",
            "kraut",
            "kum",
            "kummer",
            "kumming",
            "kums",
            "kunilingus",
            "kwif",
            "kyke",
            "l3itch",
            "labia",
            "lech",
            "len",
            "leper",
            "lesbians",
            "lesbo",
            "lesbos",
            "lez",
            "lezbian",
            "lezbians",
            "lezbo",
            "lezbos",
            "lezzie",
            "lezzies",
            "lezzy",
            "lmao",
            "lmfao",
            "loin",
            "loins",
            "lube",
            "lust",
            "lusting",
            "lusty",
            "m-fucking",
            "mafugly",
            "mams",
            "masochist",
            "massa",
            "masterb8",
            "masterbate",
            "masterbating",
            "masterbation",
            "masterbations",
            "masturbate",
            "masturbating",
            "masturbation",
            "maxi",
            "menses",
            "menstruate",
            "menstruation",
            "meth",
            "milf",
            "mofo",
            "molest",
            "moolie",
            "moron",
            "mothafuck",
            "mothafucka",
            "mothafuckas",
            "mothafuckaz",
            "mothafucked",
            "mothafucker",
            "mothafuckers",
            "mothafuckin",
            "mothafucking",
            "mothafuckings",
            "mothafucks",
            "motherfuck",
            "motherfucka",
            "motherfucked",
            "motherfucker",
            "motherfuckers",
            "motherfuckin",
            "motherfucking",
            "motherfuckings",
            "motherfuckka",
            "motherfucks",
            "mtherfucker",
            "mthrfucker",
            "mthrfucking",
            "muff",
            "muffdiver",
            "muffpuff",
            "murder",
            "mutha",
            "muthafecker",
            "muthafuckaz",
            "muthafucker",
            "muthafuckker",
            "muther",
            "mutherfucker",
            "mutherfucking",
            "muthrfucking",
            "nad",
            "nads",
            "naked",
            "napalm",
            "nappy",
            "nazi",
            "nazism",
            "needthedick",
            "negro",
            "nig",
            "nigg",
            "nigga",
            "niggah",
            "niggas",
            "niggaz",
            "nigger",
            "niggers",
            "niggle",
            "niglet",
            "nimrod",
            "ninny",
            "nipple",
            "nipples",
            "nob",
            "nobhead",
            "nobjocky",
            "nobjokey",
            "nooky",
            "nude",
            "nudes",
            "numbnuts",
            "nutbutter",
            "nutsack",
            "nympho",
            "omg",
            "opiate",
            "opium",
            "oral",
            "orally",
            "organ",
            "orgasim",
            "orgasims",
            "orgasm",
            "orgasmic",
            "orgasms",
            "orgies",
            "orgy",
            "ovary",
            "ovum",
            "ovums",
            "paddy",
            "paki",
            "pantie",
            "panties",
            "panty",
            "pastie",
            "pasty",
            "pawn",
            "pcp",
            "pecker",
            "pedo",
            "pedophile",
            "pedophilia",
            "pedophiliac",
            "pee",
            "peepee",
            "penetrate",
            "penetration",
            "penial",
            "penile",
            "penis",
            "penisfucker",
            "perversion",
            "peyote",
            "phalli",
            "phallic",
            "phonesex",
            "phuck",
            "phuk",
            "phuked",
            "phuking",
            "phukked",
            "phukking",
            "phuks",
            "phuq",
            "pigfucker",
            "pillowbiter",
            "pimp",
            "pimpis",
            "pinko",
            "piss",
            "pissed",
            "pisser",
            "pissers",
            "pisses",
            "pissflaps",
            "pissin",
            "pissing",
            "pissoff",
            "playboy",
            "pms",
            "polack",
            "pollock",
            "poon",
            "poontang",
            "poop",
            "porn",
            "porno",
            "pornography",
            "pornos",
            "pot",
            "potty",
            "prick",
            "pricks",
            "prig",
            "pron",
            "prostitute",
            "prude",
            "pube",
            "pubic",
            "pubis",
            "punkass",
            "punky",
            "puss",
            "pusse",
            "pussi",
            "pussies",
            "pussy",
            "pussyfart",
            "pussypalace",
            "pussypounder",
            "pussys",
            "puto",
            "queaf",
            "queef",
            "queer",
            "queero",
            "queers",
            "quicky",
            "quim",
            "racy",
            "rape",
            "raped",
            "raper",
            "raping",
            "rapist",
            "raunch",
            "rectal",
            "rectum",
            "rectus",
            "reefer",
            "reetard",
            "reich",
            "retard",
            "retarded",
            "revue",
            "rimjaw",
            "rimjob",
            "rimming",
            "ritard",
            "rtard",
            "rum",
            "rump",
            "rumprammer",
            "ruski",
            "sadism",
            "sadist",
            "sandbar",
            "sausagequeen",
            "scag",
            "scantily",
            "schizo",
            "schlong",
            "screw",
            "screwed",
            "screwing",
            "scroat",
            "scrog",
            "scrot",
            "scrote",
            "scrotum",
            "scrud",
            "scum",
            "seaman",
            "seamen",
            "seduce",
            "semen",
            "sex",
            "sexual",
            "shag",
            "shagger",
            "shaggin",
            "shagging",
            "shamedame",
            "shemale",
            "shibari",
            "shibary",
            "shit",
            "shitdick",
            "shite",
            "shiteater",
            "shited",
            "shitey",
            "shitface",
            "shitfuck",
            "shitfucker",
            "shitfull",
            "shithead",
            "shithole",
            "shithouse",
            "shiting",
            "shitings",
            "shits",
            "shitt",
            "shitted",
            "shitter",
            "shitters",
            "shitting",
            "shittings",
            "shitty",
            "shiz",
            "shota",
            "sissy",
            "skag",
            "skank",
            "slave",
            "sleaze",
            "sleazy",
            "slope",
            "slut",
            "slutbucket",
            "slutdumper",
            "slutkiss",
            "sluts",
            "smegma",
            "smut",
            "smutty",
            "snatch",
            "sniper",
            "snuff",
            "sob",
            "sodom",
            "son-of-a-bitch",
            "souse",
            "soused",
            "spac",
            "sperm",
            "spic",
            "spick",
            "spik",
            "spiks",
            "spooge",
            "spunk",
            "steamy",
            "stfu",
            "stiffy",
            "stoned",
            "strip",
            "strip club",
            "stripclub",
            "stroke",
            "stupid",
            "suck",
            "sucked",
            "sucking",
            "sumofabiatch",
            "tampon",
            "tard",
            "tawdry",
            "teabagging",
            "teat",
            "teets",
            "teez",
            "terd",
            "teste",
            "testee",
            "testes",
            "testical",
            "testicle",
            "testis",
            "threesome",
            "throating",
            "thrust",
            "thug",
            "tinkle",
            "tit",
            "titfuck",
            "titi",
            "tits",
            "titt",
            "tittiefucker",
            "titties",
            "titty",
            "tittyfuck",
            "tittyfucker",
            "tittywank",
            "titwank",
            "toke",
            "toots",
            "tosser",
            "tramp",
            "transsexual",
            "trashy",
            "tubgirl",
            "turd",
            "tush",
            "twat",
            "twathead",
            "twats",
            "twatty",
            "twunt",
            "twunter",
            "ugly",
            "undies",
            "unwed",
            "urinal",
            "urine",
            "uterus",
            "uzi",
            "vag",
            "vagina",
            "valium",
            "viagra",
            "vigra",
            "virgin",
            "vixen",
            "vodka",
            "vomit",
            "voyeur",
            "vulgar",
            "vulva",
            "wad",
            "wang",
            "wank",
            "wanker",
            "wanky",
            "wazoo",
            "wedgie",
            "weed",
            "weenie",
            "weewee",
            "weiner",
            "weirdo",
            "wench",
            "wetback",
            "whitey",
            "whiz",
            "whoar",
            "whoralicious",
            "whore",
            "whorealicious",
            "whored",
            "whoreface",
            "whorehopper",
            "whorehouse",
            "whores",
            "whoring",
            "wigger",
            "willies",
            "willy",
            "womb",
            "woody",
            "woose",
            "wop",
            "wtf",
            "x-rated2g1c",
            "xx",
            "xxx",
            "yaoi",
            "yury",
        ]

    def convert_leetspeak(self, text: str) -> str:
        """
        Converts leetspeak text to normal text if the result is a valid dictionary word.

        Args:
            text (str): The leetspeak text to convert

        Returns:
            str: The converted text if result is a valid word, otherwise original text
        """
        converted = text.lower()
        for leet, normal in self.replacements.items():
            converted = converted.replace(leet, normal)

        return converted

    def isBadWord(self, word: str, custom_words: list | None = None) -> bool:
        """
        Check if a word exists in the list of bad words.

        Args:
            word (str): The word to check against the bad words list
            custom_words (list): Additional custom words to add to the bad words list

        Returns:
            bool: True if the word exists in the bad words list, False otherwise
        """
        try:
            return word in self.badwords or word.lstrip().lower() in custom_words
        except TypeError:
            return False

    def isGoodWord(self, word: str) -> bool:
        if word.strip().lower() in self.goodwords:
            return True
        else:
            return False

    def predict_text(self, text) -> bool:
        """
        Predict if a single text is offensive or not.

        Args:
            text (str): The text to classify

        Returns:
            dict: Dictionary containing prediction (0 or 1) and probability
        """
        # Convert text to TF-IDF features
        text_tfidf = self.vectorizer.transform([text])

        # Get prediction
        prediction = self.model.predict(text_tfidf)[0]

        # Get probability scores
        proba = self.model.predict_proba(text_tfidf)[0]

        # print("Word is: " + text + "\n" + str(int(prediction)) + " is prediction\n" + str(float(proba[1])) + " is probation percentage")
        if int(prediction) == 1 and float(proba[1]) * 100 > 50.0:
            return True
        else:
            return False

    def textProfanityFilteration(
        self,
        profane_sentence: str,
        mask_char: str = "*",
        custom_words: list | None = None,
    ) -> list:
        """
        Filter out profanity from text and replace it with mask characters.

        This method processes input text by:
        1. Converting any leetspeak/symbols to normal text
        2. Checking each word against both ML model and bad words list
        3. Replacing profane words with mask characters
        4. Maintaining original and filtered versions in results

        Args:
            profane_sentence (str): The text to check for profanity
            mask_char (str): Character to replace profane words (e.g. "🤬", "*")
            custom_words (list | None, optional): Additional custom bad words to check. Defaults to None.

        Returns:
            list: List of dictionaries containing:
                - "OriginalWord": The original word from input
                - "IsProfane": Boolean indicating if word was profane
                - "FilteredWord": Original word or masked version if profane
        """
        # Convert any leetspeak or symbols to normal readable text
        if len(self.moderated_json) > 0:
            self.moderated_json = []  # Making the list empty

        profane_words = profane_sentence.split()

        normal_text = self.convert_leetspeak(profane_sentence)

        # Process each word in the normalized text
        for word in normal_text.split():
            if self.isGoodWord(word.lower()):
                self.moderated_json.append(
                    {
                        "OriginalWord": word,
                        "IsProfane": False,
                        "FilteredWord": word,
                    }
                )
            # Check if word is profane using ML model or exists in bad words list
            elif self.predict_text(text=word) or self.isBadWord(
                word=word, custom_words=custom_words
            ):
                # If profane, mask the word and mark as profane
                self.moderated_json.append(
                    {
                        "OriginalWord": word,
                        "IsProfane": True,
                        "FilteredWord": len(word) * mask_char,
                    }
                )
            else:
                # If not profane, keep original word and mark as clean
                self.moderated_json.append(
                    {"OriginalWord": word, "IsProfane": False, "FilteredWord": word}
                )

        # Return the list of processed words with their profanity status
        return self.moderated_json
